package com.afweb.processstockinfo;

/*  This file is generated by system. Do not modify. */
public class nnAllStock_1 {

    public static String NN_ST11 = ""
            + ""
+ "%1F%C2%8B%08%00%00%00%00%00%00%00%C2%AB%C2%AE%05%00C%C2%BF%C2%A6%C2%A3%02%00%00%00"
            + "";
}
