package com.afweb.processstockinfo;
import com.afweb.service.ServiceAFweb;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.HashMap;
/*  This file is generated by system. Do not modify. */
public class nnAllStock_1_src {

public static HashMap<String, ArrayList> AllStockHistoryStaticCodeInit(HashMap<String, ArrayList> stockInputMap) {
StringBuffer inputBuf = new StringBuffer();
try {

inputBuf.append(nnAllStock_1.NN_ST11);
String inputListSt = ServiceAFweb.decompress(inputBuf.toString());
stockInputMap = new ObjectMapper().readValue(inputListSt, HashMap.class);
return stockInputMap;
} catch (Exception ex) {
}
return stockInputMap;
}

}
