package com.afweb.nn;
import com.afweb.service.ServiceAFweb;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.HashMap;
/*  This file is generated by system. Do not modify. */
public class nnAllStock_1_src {

public static HashMap<String, ArrayList> AllStockHistoryStaticCodeInit(HashMap<String, ArrayList> stockInputMap) {
StringBuffer inputBuf = new StringBuffer();
try {

inputBuf.append(nnAllStock_1.NN_ST11);
inputBuf.append(nnAllStock_1.NN_ST12);
inputBuf.append(nnAllStock_1.NN_ST13);
inputBuf.append(nnAllStock_1.NN_ST14);
inputBuf.append(nnAllStock_1.NN_ST15);
inputBuf.append(nnAllStock_1.NN_ST16);
inputBuf.append(nnAllStock_1.NN_ST17);
inputBuf.append(nnAllStock_1.NN_ST18);
inputBuf.append(nnAllStock_1.NN_ST19);
inputBuf.append(nnAllStock_1.NN_ST110);
inputBuf.append(nnAllStock_1.NN_ST111);
inputBuf.append(nnAllStock_1.NN_ST112);
inputBuf.append(nnAllStock_1.NN_ST113);
inputBuf.append(nnAllStock_1.NN_ST114);
inputBuf.append(nnAllStock_1.NN_ST115);
inputBuf.append(nnAllStock_1.NN_ST116);
inputBuf.append(nnAllStock_1.NN_ST117);
inputBuf.append(nnAllStock_1.NN_ST118);
inputBuf.append(nnAllStock_1.NN_ST119);
inputBuf.append(nnAllStock_1.NN_ST120);
inputBuf.append(nnAllStock_1.NN_ST121);
inputBuf.append(nnAllStock_1.NN_ST122);
inputBuf.append(nnAllStock_1.NN_ST123);
inputBuf.append(nnAllStock_1.NN_ST124);
inputBuf.append(nnAllStock_1.NN_ST125);
inputBuf.append(nnAllStock_1.NN_ST126);
inputBuf.append(nnAllStock_1.NN_ST127);
inputBuf.append(nnAllStock_1.NN_ST128);
inputBuf.append(nnAllStock_1.NN_ST129);
inputBuf.append(nnAllStock_1.NN_ST130);
inputBuf.append(nnAllStock_1.NN_ST131);
inputBuf.append(nnAllStock_1.NN_ST132);
inputBuf.append(nnAllStock_1.NN_ST133);
inputBuf.append(nnAllStock_1.NN_ST134);
inputBuf.append(nnAllStock_1.NN_ST135);
inputBuf.append(nnAllStock_1.NN_ST136);
inputBuf.append(nnAllStock_1.NN_ST137);
inputBuf.append(nnAllStock_1.NN_ST138);
inputBuf.append(nnAllStock_1.NN_ST139);
inputBuf.append(nnAllStock_1.NN_ST140);
inputBuf.append(nnAllStock_1.NN_ST141);
inputBuf.append(nnAllStock_1.NN_ST142);
inputBuf.append(nnAllStock_1.NN_ST143);
inputBuf.append(nnAllStock_1.NN_ST144);
inputBuf.append(nnAllStock_1.NN_ST145);
inputBuf.append(nnAllStock_1.NN_ST146);
inputBuf.append(nnAllStock_1.NN_ST147);
inputBuf.append(nnAllStock_1.NN_ST148);
inputBuf.append(nnAllStock_1.NN_ST149);
inputBuf.append(nnAllStock_1.NN_ST150);
inputBuf.append(nnAllStock_1.NN_ST151);
inputBuf.append(nnAllStock_1.NN_ST152);
inputBuf.append(nnAllStock_1.NN_ST153);
inputBuf.append(nnAllStock_1.NN_ST154);
inputBuf.append(nnAllStock_1.NN_ST155);
inputBuf.append(nnAllStock_1.NN_ST156);
inputBuf.append(nnAllStock_1.NN_ST157);
inputBuf.append(nnAllStock_1.NN_ST158);
inputBuf.append(nnAllStock_1.NN_ST159);
inputBuf.append(nnAllStock_1.NN_ST160);
inputBuf.append(nnAllStock_1.NN_ST161);
inputBuf.append(nnAllStock_1.NN_ST162);
inputBuf.append(nnAllStock_1.NN_ST163);
inputBuf.append(nnAllStock_1.NN_ST164);
inputBuf.append(nnAllStock_1.NN_ST165);
inputBuf.append(nnAllStock_1.NN_ST166);
inputBuf.append(nnAllStock_1.NN_ST167);
inputBuf.append(nnAllStock_1.NN_ST168);
String inputListSt = ServiceAFweb.decompress(inputBuf.toString());
stockInputMap = new ObjectMapper().readValue(inputListSt, HashMap.class);
return stockInputMap;
} catch (Exception ex) {
}
return stockInputMap;
}

}
